### ISSUE TITLE
Проверка телефона на присутствие в легаси базе телефонов регистраций

### ISSUE THREAD

**Issue by Format-X22** [GolosChain/registration-service#4]
Реализовать проверку телефона на присутствие в легаси базе телефонов т.к. формат хранения данных и алгоритмов шифрования не совместим с новым форматом хранения и проверки.
Легаси данные должны храниться в отдельной коллекции и проверяться отдельным шагом на первом этапе регистрации до момента создания записи о пользователе.

**Comment by Format-X22** [comment]
Ожидаю тестового дампа базы чтобы проверить в деле.

**Comment by BaroH4er** [comment]
**Проблема:** на втором шаге регистрации - "**Верификация**", пользователь имеет возможность изменить номер телефона на уже зарегистрированный. 

![image](https://user-images.githubusercontent.com/21989598/46011640-2bc69d00-c0cf-11e8-91c7-d3b254e2c827.png)

- [ ] FIXED

**Решение:** необходимо добавить проверку телефона на присутствие в легаси базе телефонов регистраций. В случае присутствия телефона в легасе, сообщать об этом пользователю и не менять номер телефона, введенного на первом шаге.

**Comment by BaroH4er** [comment]
Done
