### ISSUE TITLE
Обновление регистрации. Поддержка доменных имен. 

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/registration-service#69]
Необходимо реализовать поддержку установки доменного имени для пользователя. 

Документация 

https://github.com/GolosChain/cyberway.contracts/blob/master/docs/ru-RU/cyber.domain_contract.md#%D0%BE%D0%B1%D1%8A%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-newusername

1. Имя аккаунта (12,5 символов) необходимо генерировать. 
2. Осуществляем проверку сгенерированного имени, на наличие коллизий в БЧ
3. Произвести регистрацию аккаунта в БЧ, с добавлением нового экшена newusername (дока выше)
4. В ответе необходимо возвращать имя аккаунта и алиас.

**Comment by beautyfree** [comment]
Необходимо добавить экшен newusername контракта cyber.domain в [цепочку экшенов](https://github.com/GolosChain/registration-service/blob/develop/src/controllers/Abstract.js#L54), который принимает 3 аргумента: 
1. creator - аккаунт владельца домена строкой
2. owner - сгенерированное имя аккаунта (12,5 символов)
3. name - алиас имя аккаунта для owner, полученное от пользователя

Для выполнения этого экшена требуется наличие ключа от creator в [массив ключей](https://github.com/GolosChain/registration-service/blob/develop/src/controllers/Abstract.js#L12)
