### ISSUE TITLE
Поменять логику waitForTransaction

### ISSUE THREAD

**Issue by IvanBlacky** [GolosChain/registration-service#75]
На этапе toBlockChain один раз попробовать дождаться транзакции в призме. Если время ожидания превышено, то через 10 секунд вернуть OK

**Comment by Format-X22** [comment]
А почему ок?

**Comment by IvanBlacky** [comment]
> А почему ок?

Неправильно сформулировал мысль. Имеется в виду: вернуть тот ответ, который возвращается при успешном завершении шага
